apiVersion: v1
kind: ConfigMap
metadata:
  name: robot-master-config
  namespace: robot-master
data:
  master.yaml: |
    listen: ":8080"
    redis-addr: "redis.robot-master.svc.cluster.local:6379"
    redis-pwd: ""
    report-dir: "/data/report"
