apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: robot-master-report
  namespace: robot-master
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # storageClassName: standard  # 按集群实际情况指定
